
setup:
    slices_2d: False
    global_scale: 20

save:
    group_name: "roa_sweep/tests"
    run_name: "param_set_00001"

simulation:
    time_step: 0.0005
    gravity: -196.2 #-9.81
    gui: True
    video: True
    camera:
        width: 1920
        height: 1080
        distance: 3.5
        pitch: -50
        yaw: 180
        target: [1, 0, 1.0]

manipulator:
    fingers: 
        file: "definitions/2seg_finger_def.yaml"
        distal_seg_ratio: 0.5
        offset:
            position:    [2.0,0,0]
            orientation: [0,0,0] # Not used yet...
        poses:
            - position:    [0,-0.5,0]
              orientation: [15, -90 , 0]
            - position:    [0, 0.5, 0]
              orientation: [15, 90 ,180]
        lateral_friction:  2.0
        #spinning_friction: 2.0
        restitution:       1
        
    hand:
        position:    [-0.2, 0, 0.2]
        orientation: [0,0,0] # Not used yet...


    motion:
        fingers:
            file: "actuation/fingers_grasp_strong.yaml"
            num_reps:         1.0
            speed_factor:     1.0
            invert_direction: True

        hand:
            file: "actuation/hand_motions/hand_side_position.yaml"
            num_reps:         1.0
            speed_factor:     1.0
            invert_direction: False


object:
    file: "objects/object_set/cube_60mm/CubeLifeSize_v2_60_60.urdf" #"objects/smallBall.urdf"
    above_ground: 0.01
    position: [0.0, 0.0, 2.5]
    orientation: [0, 0, 0]
    lateral_friction:  2.0